apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kruise-repo
  namespace: kruise-system
spec:
  url: https://github.com/openkruise/kruise
  ref:
    branch: master
  interval: 5m