apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kruise-release
  namespace: kruise-system
  annotations:
    meta.helm.sh/release-name: kruise-release
    meta.helm.sh/release-namespace: kruise-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/kruise/v0.9.0
      sourceRef:
        kind: GitRepository
        name: kruise-repo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
