apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: appconfig-scaler
spec:
  components:
    - componentName: component-scaler
      traits:
        - trait:
            apiVersion: standard.oam.dev/v1alpha1
            kind: Autoscaler
            metadata:
              name: trait-scaler
            spec:
              minReplicas: 2
              maxReplicas: 10
              triggers:
                - name: weekday-cron
                  enabled: true
                  type: cron
                  condition:
                    startAt: "19:01"
                    duration: 2h
                    days: ["Monday", "Tuesday"]
                    replicas: 3
                    timezone: Asia/Shanghai
                - name: cpu-resource-utilization
                  enabled: true
                  type: cpu
                  condition:
                    target: 5
