apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-controller
subjects:
  - kind: ServiceAccount
    name: kustomize-controller-serviceaccount
    namespace: vela-system
  - kind: ServiceAccount
    name: helm-controller-serviceaccount
    namespace: vela-system
  - kind: ServiceAccount
    name: source-controller-serviceaccount
    namespace: vela-system