apiVersion: v1
kind: Namespace
metadata:
  name: vela-system
spec: {}
status: {}
---
apiVersion: core.oam.dev/v1beta1
kind: Initializer
metadata:
  annotations:
    addons.oam.dev/description: Kruise is a Kubernetes extended suite for application automations
  name: kruise
  namespace: vela-system
spec:
  appTemplate:
    spec:
      components:
      - name: kruise-release
        properties:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            annotations:
              meta.helm.sh/release-name: kruise-release
              meta.helm.sh/release-namespace: kruise-system
            labels:
              app.kubernetes.io/managed-by: Helm
            name: kruise-release
            namespace: kruise-system
          spec:
            chart:
              spec:
                chart: ./charts/kruise/v0.9.0
                interval: 1m
                sourceRef:
                  kind: GitRepository
                  name: kruise-repo
                  namespace: flux-system
            interval: 5m
            values:
              replicaCount: 1
        type: raw
      - name: kruise-repo
        properties:
          apiVersion: source.toolkit.fluxcd.io/v1beta1
          kind: GitRepository
          metadata:
            name: kruise-repo
            namespace: kruise-system
          spec:
            interval: 5m
            ref:
              branch: master
            url: https://github.com/openkruise/kruise
        type: raw
      - name: kruise-system
        properties:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: kruise-system
        type: raw
    status:
      rollout:
        batchRollingState: ""
        currentBatch: 0
        lastTargetAppRevision: ""
        rollingState: ""
        upgradedReadyReplicas: 0
        upgradedReplicas: 0
  dependsOn:
  - ref:
      apiVersion: core.oam.dev/v1beta1
      kind: Initializer
      name: fluxcd
      namespace: vela-system
status:
  observedGeneration: 0
