apiVersion: core.oam.dev/v1beta1
kind: Initializer
metadata:
  annotations:
    addons.oam.dev/description: Prometheus is an open-source systems monitoring and alerting toolkit
  name: prometheus
  namespace: prometheus
spec:
  appTemplate:
    spec:
      components:
      - name: prometheus
        properties:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: prometheus
            namespace: prometheus
          spec:
            chart:
              spec:
                chart: premetheus
                interval: 1pm
                sourceRef:
                  kind: HelmRepository
                  name: prometheus-community
                  namespace: premetheus
            interval: 5m
        type: raw
      - name: prometheus-community
        properties:
          apiVersion: source.toolkit.fluxcd.io/v1beta1
          kind: HelmRepository
          metadata:
            name: prometheus-community
            namespace: prometheus
          spec:
            interval: 1m
            url: https://prometheus-community.github.io/helm-charts
        type: raw
    status:
      rollout:
        batchRollingState: ""
        currentBatch: 0
        lastTargetAppRevision: ""
        rollingState: ""
        upgradedReadyReplicas: 0
        upgradedReplicas: 0
  dependsOn:
  - ref:
      apiVersion: core.oam.dev/v1beta1
      kind: Initializer
      name: fluxcd
      namespace: flux-system
status:
  observedGeneration: 0
