apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: manualscalertraits.core.oam.dev
  annotations:
    definition.oam.dev/apiVersion: "core.oam.dev/v1alpha2"
    definition.oam.dev/kind: "ManualScalerTrait"
spec:
  appliesToWorkloads:
    - core.oam.dev/v1alpha2.ContainerizedWorkload
  definitionRef:
    name: manualscalertraits.core.oam.dev
  extension:
    template: |
      #Template: {
      	apiVersion: "core.oam.dev/v1alpha2"
      	kind:       "ManualScalerTrait"
      	spec: {
      		replicaCount: scale.replica
      	}
      }
      scale: {
      	//+short=r
      	replica: *2 | int
      }
