apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: rollout-demo-app
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rollout-demo-app
      labels:
        app: rollout-demo-app
        # pod-template-hash: 7564juhy8m6n785i
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: rollout-demo-app
      template:
        metadata:
          labels:
            app: rollout-demo-app
            # pod-template-hash: 7564juhy8m6n785i
        spec:
          containers:
            - image: luxas/autoscale-demo:v0.1.1
              name: metrics-provider
              ports:
                - name: http
                  containerPort: 8080
