apiVersion: core.oam.dev/v1alpha2
kind: AppRollout
metadata:
  name: rolling-test
spec:
  # application (revision) reference
  targetApplicationName: test-rolling-v2
  sourceApplicationName: test-rolling-v1
  # HPA reference (optional)
  componentList:
    - metrics-provider
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    rolloutBatches:
      - replicas: 10%
      - replicas: 2
      - replicas: 2
    batchPartition: 1
