apiVersion: core.oam.dev/v1alpha2
kind: AppRollout
metadata:
  name: rolling-test
spec:
  # application (revision) reference
  targetAppRevisionName: test-rolling-v3
  sourceAppRevisionName: test-rolling-v2
  # HPA reference (optional)
  componentList:
    - metrics-provider
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    rolloutBatches:
      - replicas: 20%
      - replicas: 30%
      - replicas: 50%