apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: autoscalers.standard.oam.dev
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: Autoscaler
spec:
  appliesToWorkloads:
    - core.oam.dev/v1alpha2.webservice
    - core.oam.dev/v1alpha2.backend
    - core.oam.dev/v1alpha2.task
    - deployments.apps
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: autoscalers.standard.oam.dev