apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-config
  namespace: default
data:
  certificates.cert-manager.io: |
    {
      "repo": "jetstack",
      "urL": "https://charts.jetstack.io",
      "name": "cert-manager",
      "version": "v1.0.0"
    },