apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: testapp
spec:
  components:
    - name: express-server
      scopes:
        healthscopes.core.oam.dev: testapp-default-health
      settings:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        port: 8080
      traits:
        - name: new-route
          properties:
            domain: test.my.domain
            http:
              "/api": 8080
      type: webservice