apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: testapp4
spec:
  components:
    - name: express-server4
      type: webserver
      settings:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        port: 8080