apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "add env into your pods"
  name: podenv
spec:
  appliesToWorkloads:
    - webservice
    - worker
  extension:
    template: |-
      patch: {
      	spec: template: spec: {
      		// +patchKey=name
      		containers: [{
      			name: context.name
      			// +patchKey=name
      			env: [
      				for k, v in parameter.env {
      					name:  k
      					value: v
      				},
      			]
      		}]
      	}
      }

      parameter: {
      	env: [string]: string
      }

