apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: testapp
spec:
  components:
    - name: express-server
      type: webservice
      settings:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        port: 8080
        env:
          - name: abc
            value: abc1
      traits:
        - name: "podenv"
          properties:
            env:
              xyz: "haha1"
              nihao: "haha2"
