apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000
  policies:
    - name: my-policy
      type: foopolicy
      properties:
        key: test

  workflow:
    - name: my-wf
      type: foowf
      properties:
        key: test
