apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: task
  annotations:
    definition.oam.dev/apiVersion: "v1"
    definition.oam.dev/kind: "Job"
    definition.oam.dev/description: "One-time task/job"
spec:
  definitionRef:
    name: jobs
  extension:
    template: |
      output: {
      	apiVersion: "v1"
      	kind:       "Job"
      	spec: {
      		parallelism: parameter.count
      		completions: parameter.count
      		template: spec: {
      			containers: [{
      				name:  context.name
      				image: parameter.image
      
      				if parameter["cmd"] != _|_ {
      					command: parameter.cmd
      				}
      			}]
      		}
      	}
      }
      parameter: {
      	// +usage=specify number of tasks to run in parallel
      	// +short=c
      	count: *1 | int
      
      	// +usage=Which image would you like to use for your service
      	// +short=i
      	image: string
      
      	cmd?: [...string]
      }
      
