
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - core.oam.dev
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.oam.dev
  resources:
  - '*/status'
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*/status'
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - standard.oam.dev
  resources:
  - metricstraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - standard.oam.dev
  resources:
  - metricstraits/status
  verbs:
  - get
  - patch
  - update
