apiVersion: core.oam.dev/v1beta1
kind: Initializer
metadata:
  annotations:
    addons.oam.dev/description: "Flux is a set of continuous and progressive delivery solutions for Kubernetes"
  name: fluxcd
  namespace: vela-system
spec:
  appTemplate:
    spec:
      components: {{  range .Files  }}
      - name: {{ .Name }}
        type: raw
        properties:
{{ .Content }} {{ end }}