apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: component-scaler
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx-scaler
              image: nginx:1.9.4
              ports:
                - containerPort: 80
                  name: nginx
