apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: application-sample
spec:
  services:
    myweb:
      type: worker
      image: "busybox"
      cmd:
      - sleep
      - "1000"
      scaler:
        replicas: 10
      sidercar:
        name: "sidecar-test"
        image: "nginx"
      service:
        http:
          server: 80