apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: test-rolling
spec:
  components:
    - name: metrics-provider
      type: clonesetservice
      settings:
        cmd:
          - ./podinfo
          - stress-cpu=1
        image: stefanprodan/podinfo:4.0.6
        port: 8080
        updateStrategyType: InPlaceIfPossible