apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: myworker
spec:
  definitionRef:
    name: deployments.apps
  schematic:
    cue:
      template: |
        import (
           apps "kube/apps/v1"
        )
        output: apps.#Deployment
        output: {
        	spec: {
        		selector: matchLabels: {
        			"app.oam.dev/component": context.name
        		}

        		template: {
        			metadata: labels: {
        				"app.oam.dev/component": context.name
        			}

        			spec: {
        				containers: [{
        					name:  context.name
        					image: parameter.image

        					if parameter["cmd"] != _|_ {
        						command: parameter.cmd
        					}
        				}]
        			}
        		}
        	}
        }

        parameter: {
        	// +usage=Which image would you like to use for your service
        	// +short=i
        	image: string
        	// +usage=Commands to run in the container
        	cmd?: [...string]
        }

