apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: autoscale
  annotations:
    definition.oam.dev/description: "`Autoscale` is used to automatically scale workloads by resource utilization metrics or cron triggers."
spec:
  appliesToWorkloads:
    - webservice
    - worker
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: autoscalers.standard.oam.dev
  extension:
    template: |
