apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: autoscale
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: Autoscaler
    definition.oam.dev/description: "Automatically scale workloads"
spec:
  appliesToWorkloads:
    - webservice
    - backend
    - deployments.apps
    - podspecworkload
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: autoscalers.standard.oam.dev
  extension:
    template: |
