apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metric
  annotations:
    definition.oam.dev/description: "Configure metrics targets to be monitored for the app"
spec:
  appliesToWorkloads:
    - webservice
    - backend
    - task
  definitionRef:
    name: metricstraits.standard.oam.dev
  workloadRefPath: spec.workloadRef
  extension:
    template: |-
