apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metrics
  annotations:
    definition.oam.dev/description: "`Metrics` is used to configure monitoring metrics for your service."
spec:
  appliesToWorkloads:
    - webservice
    - backend
    - task
  definitionRef:
    name: metricstraits.standard.oam.dev
  workloadRefPath: spec.workloadRef
  extension:
    template: |-
