apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: rollout
  annotations:
    definition.oam.dev/description: "`Rollout` is used to configure Canary deployment strategy for your application."
spec:
  appliesToWorkloads:
    - webservice
  definitionRef:
    name: canaries.flagger.app
  workloadRefPath: spec.targetRef
  revisionEnabled: true
  extension:
    template: |-
