apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: route
  annotations:
    definition.oam.dev/description: "`Route` is used to configure external access to your service."
spec:
  appliesToWorkloads:
    - webservice
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: routes.standard.oam.dev
  extension:
    template: |
