apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "binding cloud resource secrets to pod env"
  name: service-binding
  namespace: {{.Values.systemDefinitionNamespace}}
spec:
  appliesToWorkloads:
    - webservice
    - worker
  schematic:
    cue:
      template: |
