apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: task
  namespace: {{.Values.systemDefinitionNamespace}}
  annotations:
    definition.oam.dev/description: "Describes jobs that run code or a script to completion."
spec:
  definitionRef:
    name: jobs.batch
  schematic:
    cue:
      template: |
