apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: task
  annotations:
    definition.oam.dev/description: "One-off task to run a piece of code or script to completion"
spec:
  definitionRef:
    name: jobs
  extension:
    template: |
