apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: task
  namespace: {{.Values.systemDefinitionNamespace}}
  annotations:
    definition.oam.dev/description: "Describes jobs that run code or a script to completion."
spec:
  workload:
    definition:
      apiVersion: batch/v1
      kind: Job
  schematic:
    cue:
      template: |
