apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: webservice
  annotations:
    definition.oam.dev/description: "Long-running scalable service with stable endpoint to receive external traffic"
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
