apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: backend
  annotations:
    definition.oam.dev/apiVersion: "apps/v1"
    definition.oam.dev/kind: "Deployment"
    definition.oam.dev/description: "Backend worker without ports exposed"
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
