apiVersion: core.oam.dev/v1alpha2
kind: AppDeployment
metadata:
  name: example-appdeploy
spec:
  appRevisions:
    - revisionName: example-app-v1

      placement:
        - distribution:
            replicas: 2
