apiVersion: core.oam.dev/v1beta1
kind: Initializer
metadata:
  annotations:
    addons.oam.dev/description: "Terraform Controller is a Kubernetes Controller for Terraform."
  name: terraform
  namespace: vela-system
spec:
  dependsOn:
    - ref:
        apiVersion: core.oam.dev/v1beta1
        kind: Initializer
        name: fluxcd
        namespace: vela-system
  appTemplate:
    spec:
      components: {{  range .ResourceFiles  }}
        - name: {{ .Name }}
          type: raw
          properties:
{{ .Content | indent 12 }} {{ end }}