
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: templates.admin.oam.dev
spec:
  group: admin.oam.dev
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: ""
  validation:
    openAPIV3Schema:
      description: Template is the Schema for the templates API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TemplateSpec defines the desired state of Template
          properties:
            lastCommandParam:
              type: string
            object:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: object
            parameters:
              items:
                properties:
                  default:
                    type: string
                  fieldPaths:
                    items:
                      type: string
                    type: array
                  name:
                    type: string
                  required:
                    type: boolean
                  short:
                    type: string
                  type:
                    type: string
                  usage:
                    type: string
                required:
                - fieldPaths
                - name
                type: object
              type: array
          required:
          - object
          type: object
        status:
          description: TemplateStatus defines the observed state of Template
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
