apiVersion: v1
data:
  initializer: |
    apiVersion: core.oam.dev/v1beta1
    kind: Initializer
    metadata:
      annotations:
        addons.oam.dev/description: KEDA is a Kubernetes-based Event Driven Autoscaler.
      name: keda
      namespace: keda
    spec:
      appTemplate:
        spec:
          components:
          - name: keda
            properties:
              apiVersion: helm.toolkit.fluxcd.io/v2beta1
              kind: HelmRelease
              metadata:
                name: keda
                namespace: keda
              spec:
                chart:
                  spec:
                    chart: keda
                    interval: 1m
                    sourceRef:
                      kind: HelmRepository
                      name: kedacore
                      namespace: keda
                    version: 2.3.2
                interval: 5m
                values:
                  replicaCount: 1
            type: raw
          - name: kedacore
            properties:
              apiVersion: source.toolkit.fluxcd.io/v1beta1
              kind: HelmRepository
              metadata:
                name: kedacore
                namespace: keda
              spec:
                interval: 1m
                url: https://kedacore.github.io/charts
            type: raw
        status:
          rollout:
            batchRollingState: ""
            currentBatch: 0
            lastTargetAppRevision: ""
            rollingState: ""
            upgradedReadyReplicas: 0
            upgradedReplicas: 0
      dependsOn:
      - ref:
          apiVersion: core.oam.dev/v1beta1
          kind: Initializer
          name: fluxcd
          namespace: flux-system
    status:
      observedGeneration: 0
kind: ConfigMap
metadata:
  annotations:
    addons.oam.dev/description: KEDA is a Kubernetes-based Event Driven Autoscaler.
  labels:
    addons.oam.dev/type: keda
  name: keda
  namespace: {{.Values.systemDefinitionNamespace}}
