apiVersion: v1
data:
  initializer: |
    apiVersion: core.oam.dev/v1beta1
    kind: Initializer
    metadata:
      annotations:
        addons.oam.dev/description: Terraform Controller is a Kubernetes Controller for Terraform.
      name: terraform
      namespace: vela-system
    spec:
      appTemplate:
        spec:
          components:
          - name: tc-system
            properties:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: tc-system
            type: raw
          - name: terraform-controller-release
            properties:
              apiVersion: helm.toolkit.fluxcd.io/v2beta1
              kind: HelmRelease
              metadata:
                name: terraform-controller-release
                namespace: tc-system
              spec:
                chart:
                  spec:
                    chart: ./chart
                    interval: 1m
                    sourceRef:
                      kind: GitRepository
                      name: terraform-controller-repo
                      namespace: tc-system
                interval: 5m
                values:
                  replicaCount: 1
            type: raw
          - name: terraform-controller-repo
            properties:
              apiVersion: source.toolkit.fluxcd.io/v1beta1
              kind: GitRepository
              metadata:
                name: terraform-controller-repo
                namespace: tc-system
              spec:
                interval: 5m
                ref:
                  branch: master
                url: https://github.com/oam-dev/terraform-controller
            type: raw
        status:
          rollout:
            batchRollingState: ""
            currentBatch: 0
            lastTargetAppRevision: ""
            rollingState: ""
            upgradedReadyReplicas: 0
            upgradedReplicas: 0
      dependsOn:
      - ref:
          apiVersion: core.oam.dev/v1beta1
          kind: Initializer
          name: fluxcd
          namespace: vela-system
    status:
      observedGeneration: 0
kind: ConfigMap
metadata:
  annotations:
    addons.oam.dev/description: Terraform Controller is a Kubernetes Controller for Terraform.
  labels:
    addons.oam.dev/type: terraform
  name: terraform
  namespace: {{.Values.systemDefinitionNamespace}}
