name: docs
on:
  pull_request:
    paths:
      - 'docs/**'
    branches:
      - master
      - release-*
jobs:
  latest:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v1
      - name: Push to GitHub Repo
        uses: sunny0826/auto-docs-action@v0.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GH_PAGES_DEPLOY }}
        with:
          gh-page: git@github.com:oam-dev/kubevela.io.git
  released:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v1
      - name: Push to GitHub Repo
        uses: sunny0826/auto-docs-action@v0.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GH_PAGES_DEPLOY }}
          VERSION: ${{ github.ref }}
        with:
          gh-page: git@github.com:oam-dev/kubevela.io.git