name: E2E

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths-ignore:
    - 'docs/**'
    - '**.md'

jobs:
  build:
    name: e2e-tests
    runs-on: aliyun
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Setup Kind Cluster
        uses: engineerd/setup-kind@v0.4.0
        with:
          version: "v0.7.0"
          skipClusterCreation: true

      - name: Setup Kind Cluster
        run: |
          kind delete cluster
          kind create cluster
          kubectl version
          kubectl cluster-info

      - name: Load Image to kind cluster
        run: make kind-load

      - name: Run Make
        run: make

      - name: Run Make Manager
        run: make manager

      - name: Run e2e tests
        run: |
          make e2e-cleanup
          make e2e-setup
          make e2e-test
          make e2e-api-test
