apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: autoscale
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "Automatically scales workloads by resource utilization metrics or cron triggers."
spec:
  appliesToWorkloads:
    - deployments.apps
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: autoscalers.standard.oam.dev
  podDisruptive: true
  extension:
    install:
      helm:
        repo: kedacore
        name: keda
        url: https://kedacore.github.io/charts
        version: 2.0.0-rc3
  schematic:
    cue:
      template: |
