apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: metrics
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "Configures monitoring metrics for your service."
spec:
  appliesToWorkloads:
    - deployments.apps
    - jobs.batch
  definitionRef:
    name: metricstraits.standard.oam.dev
  workloadRefPath: spec.workloadRef
  extension:
    install:
      helm:
        repo: prometheus-community
        name: kube-prometheus-stack
        namespace: monitoring
        url: https://prometheus-community.github.io/helm-charts
        version: 9.4.4
  schematic:
    cue:
      template: |-
