apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: rollout
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "Configures Canary deployment strategy for your application."
spec:
  appliesToWorkloads:
    - deployments.apps
  definitionRef:
    name: canaries.flagger.app
  workloadRefPath: spec.targetRef
  revisionEnabled: true
  podDisruptive: true
  extension:
    install:
      helm:
        repo: oam-flagger
        name: flagger
        namespace: vela-system
        url: https://oam.dev/flagger/archives/
        version: 1.1.0
  schematic:
    cue:
      template: |-
